// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYhLuc2DJv4ntQuAfMpBi5fPlxJLUka88',
    appId: '1:478640854089:web:7a26ce6f8ae16a8f3e5b98',
    messagingSenderId: '478640854089',
    projectId: 'fir-auth-testing-f6598',
    authDomain: 'fir-auth-testing-f6598.firebaseapp.com',
    storageBucket: 'fir-auth-testing-f6598.firebasestorage.app',
    measurementId: 'G-XE3G2C5E2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9HEgyLMOij6YaQRT5Z2DlmDLthXAmHbU',
    appId: '1:478640854089:android:4b78a23d7c98be533e5b98',
    messagingSenderId: '478640854089',
    projectId: 'fir-auth-testing-f6598',
    storageBucket: 'fir-auth-testing-f6598.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3SPEye6ZrWMVuI1g9K9u5KFJi-k1pflQ',
    appId: '1:478640854089:ios:f86b11d9658caf8e3e5b98',
    messagingSenderId: '478640854089',
    projectId: 'fir-auth-testing-f6598',
    storageBucket: 'fir-auth-testing-f6598.firebasestorage.app',
    iosBundleId: 'com.example.projectLbsWorship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3SPEye6ZrWMVuI1g9K9u5KFJi-k1pflQ',
    appId: '1:478640854089:ios:f86b11d9658caf8e3e5b98',
    messagingSenderId: '478640854089',
    projectId: 'fir-auth-testing-f6598',
    storageBucket: 'fir-auth-testing-f6598.firebasestorage.app',
    iosBundleId: 'com.example.projectLbsWorship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYhLuc2DJv4ntQuAfMpBi5fPlxJLUka88',
    appId: '1:478640854089:web:cd6a16e2a60931063e5b98',
    messagingSenderId: '478640854089',
    projectId: 'fir-auth-testing-f6598',
    authDomain: 'fir-auth-testing-f6598.firebaseapp.com',
    storageBucket: 'fir-auth-testing-f6598.firebasestorage.app',
    measurementId: 'G-PXJGQV875V',
  );
}
